In [1]:
import numpy as np 
np.arange(10,30,5)

array([10, 15, 20, 25])

In [2]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
import numpy as np 
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
print(a[0,1])

1


In [6]:
import numpy as np
np.empty( (2,3) )

array([[2.04271797e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [8]:
import numpy as np 
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
import numpy as np
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [18]:
import numpy as np
a=np.random.random((2,3))
print(a)

[[0.156681   0.36269198 0.84034348]
 [0.12234597 0.3946884  0.11010069]]


In [19]:
import numpy as np
a=np.array([20,30,40,50])
b=np. arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]
